name: docker-build

on:
  push:
    branches:
      - master
    paths:
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Find changed Dockerfiles and build/push
        run: |
          git fetch origin master
          # FILES=$(git diff --name-only origin/master...HEAD | grep '/Dockerfile$' || true)
          FILES=$(git diff --name-only origin/master | grep '/Dockerfile$' || true)

          if [ -z "$FILES" ]; then
            echo "No Dockerfiles changed."
            exit 0
          fi

          for FILE in $FILES; do
            DIR=$(dirname "$FILE")
            DIRNAME=$(basename "$DIR")
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${DIRNAME}:latest"

            echo "Building and pushing $IMAGE_NAME from $FILE"

            docker buildx build \
              --file "$FILE" \
              --tag "$IMAGE_NAME" \
              --push \
              "$DIR"
          done

